### ISSUE TITLE
Update to v1.3.3

### ISSUE THREAD

**Issue by davendrajayasingam** [ulitcos/react-canvas-confetti#1]
There is an issue when building on Gatsby, mentioned here #https://github.com/catdad/canvas-confetti/issues/78

It has been fixed in v1.3.3 and requires an update to the dependency.

Thanks!

**Comment by ulitcos** [comment]
Thanks for report. Fix it in [1.1.1 version](https://www.npmjs.com/package/react-canvas-confetti/v/1.1.1)
