### ISSUE TITLE
New star shape breaks Typescript

### ISSUE THREAD

**Issue by matyus** [ulitcos/react-canvas-confetti#11]
https://github.com/catdad/canvas-confetti/pull/189
https://github.com/DefinitelyTyped/DefinitelyTyped/pull/62880

Example error

<img width="1256" alt="Screen Shot 2023-03-26 at 5 02 41 PM" src="https://user-images.githubusercontent.com/1214020/227804525-383a32c3-fba6-4271-81fd-03af9af53800.png">

**Comment by ulitcos** [comment]
Hi @matyus. Thanks for the report.
I published a new version with @types/canvas-confetti@1.6.0. Now you can fix the problem with typings by installing react-canvas-confetti@1.4.0.

**Comment by matyus** [comment]
thanks for the expediency!
