### ISSUE TITLE
Preset style throw errors on compilation time

### ISSUE THREAD

**Issue by EricBatlle** [ulitcos/react-canvas-confetti#13]
Hi, I'm trying to use your package and component like:
const canvasStyles = {
    position: "fixed",
    pointerEvents: "none",
    width: "100%",
    height: "100%",
    top: 0,
    left: 0,
  };
<Pride autorun={{ speed: 30, duration:3000 }} style={canvasStyles} />

But compiler get's the error:
```
Type error: Type '{ position: string; pointerEvents: string; width: string; height: string; top: number; left: number; }' is not assignable to type 'Properties<string | number, string & {}>'.
  Types of property 'pointerEvents' are incompatible.
    Type 'string' is not assignable to type 'PointerEvents | undefined'.
```

How can I fix it?

**Comment by ulitcos** [comment]
Hi! You can fix it by adding type CSSProperties to canvasStyles variable like this

```typescript
import { CSSProperties } from "react";

const canvasStyles: CSSProperties = {
  position: "fixed",
  pointerEvents: "none",
  width: "100%",
  height: "100%",
  top: 0,
  left: 0,
};

<Pride autorun={{ speed: 30, duration: 3000 }} style={canvasStyles} />;
```

I also added [live example](https://codesandbox.io/p/devbox/pride-issue-react-canvas-confetti-v2-h9dhzh)

**Comment by EricBatlle** [comment]
Thank you very much @ulitcos, it fixes the issue.
If you accept suggestions, I'll add this on your other presets examples, it was the reason that I stumbled across this issue ^^'

**Comment by ulitcos** [comment]
Yes, thank you. I fixed examples.
