### ISSUE TITLE
Customize explosion count

### ISSUE THREAD

**Issue by bullishgopher** [ulitcos/react-canvas-confetti#15]
I want to have `multiple explosions` at `once`. 
For example, in `Fireworks` example, has 2 explosions, and other examples have 1 explosion at once.
Can we customize the number of explosions for each example?

- [x] have multiple explosions at a time
- [x] each explosion position would be randomized

**Comment by bullishgopher** [comment]
```typescript
import { useState } from "react";
import { TConductorInstance } from "react-canvas-confetti/dist/types";
import Explosion from "react-canvas-confetti/dist/presets/explosion";

interface BombExplosionProps {
  count: number
}
function BombExplosion({ count }: BombExplosionProps) {
  const newArray: number[] = Array.from({ length: count }, (_, index) => index + 1);

  const [conductor, setConductor] = useState<TConductorInstance[]>([]);


  const onOnce = () => {
    conductor.forEach(c => c.shoot())
  };

  const onInit = (conductor: TConductorInstance, fireworkId: number) => {
    setConductor(prev => {
      const prevArr = [...prev]
      prevArr.push(conductor)
      return prevArr
    });
  };

  return (
    <>
      <div className={"controls"}>
        <button onClick={onOnce}>Once</button>

      </div>
      {newArray.map(arr => {
        return (<Explosion onInit={({ conductor }) => onInit(conductor, arr)} key={arr} />)
      })
      }
    </>
  );
}

export default BombExplosion;
```

This is the code example that I used. But it shows the explosions in one place.

---
If I use <Fireworks /> component, it shows multiple explosions in different positions, but explosion count is multiplied by 2
For example, if I load two <Fireworks /> component, it shows 4 explosions.

**Comment by bullishgopher** [comment]
cc @ulitcos 👆

**Comment by ulitcos** [comment]
Hi there! 

> have multiple explosions at a time

I think you can solve your problem by using a combination of parameters for the `run` method. The run method takes a `duration` in ms (1000 ms is 1 second) and a `speed` (shots per second). So, you need to find the right values. For example, you can set a `speed` of 1000 and a `duration` of 2 and get two shots in one run call. You have to remember that the preset explosion makes two shots in one method call, so maybe you need to divide by 2!

> each explosion position would be randomized

This problem can be solved by passing the `decorateOptions` parameter with the updated `origin` parameter.

Anyway, I've created an [example](https://codepen.io/ulitcos/pen/RwddxaB?editors=0010) for you. Just play with the `speed`, `duration` and `decorateOptions`.

**Comment by bullishgopher** [comment]
Thanks!! It works like a charm 😁

**Comment by bullishgopher** [comment]
@ulitcos 
I have two questions for your second example.

- instead of using star, I am gonna use circle. but the circles are rotating. stars were not. can we make those circles to not rotate?

- is it possible to make the real bomb explosion using `react-canvas-confetti` ?

**Comment by ulitcos** [comment]
> instead of using star, I am gonna use circle. but the circles are rotating. stars were not. can we make those circles to not rotate?

You can add `flat: true` in params. [Example](https://codepen.io/ulitcos/pen/KKYPgPy?editors=0010)

> is it possible to make the real bomb explosion using react-canvas-confetti ?

Absolutely not! This is against the law!

**Comment by bullishgopher** [comment]
Thanks!!

**Comment by piotr-cz** [comment]
Another option could be custom Conductor, which would increment and test iterations on `shoot` and reset on `stop`
