### ISSUE TITLE
Release notes?

### ISSUE THREAD

**Issue by sami-eljabali** [ulitcos/react-canvas-confetti#18]
Hi @ulitcos! 

Thanks for the project. Great work 😃 

I've updated from 1.4.0 to 2.0.7 and found our confetti animation broken.

I didn't see any release notes to what happened from v1 to v2 to help debug the issue.

Is it possible to maintain release notes with new tags?

Also any hints what you think may have caused the issue would be of great help!

Thanks!

**Comment by ulitcos** [comment]
@seljabali, thank you for your report. In short, everything has changed. Version 2 is a completely new library.

I'm afraid that the list of changes will not help in this case. I respect the [server](https://github.com/semver/semver/blob/master/semver.md), which means that the major version changes contain interface changes and these changes break backward compatibility. In fact, version 2 is a new library. In this case, it makes no sense to focus on the differences between the first and second versions. It would be more effective to just read the readme in full and see the new code examples. If you have an urgent need to move to a new major version, but you cannot fix the error, then send me examples of your code. I'm sure we can solve them together.

**Comment by sami-eljabali** [comment]
Got it. Thank you so much! 

I'll read over the README and play it from there.

Best!
