### ISSUE TITLE
An example with Functional Component in React

### ISSUE THREAD

**Issue by prince272** [ulitcos/react-canvas-confetti#4]

**Comment by MartinSeeler** [comment]
Did you find a solution for this? I am currently struggeling.

**Comment by ulitcos** [comment]
@MartinSeeler, hi.

I have collected examples for functional and class components and added them to [readme](https://github.com/ulitcos/react-canvas-confetti#examples)

![image](https://user-images.githubusercontent.com/4023479/142741219-1f6ab31c-9f15-4521-9ee3-bb8fc54e2a5f.png)
