### ISSUE TITLE
Set the fireworks work on timer

### ISSUE THREAD

**Issue by xdominus** [ulitcos/react-canvas-confetti#5]
I made an array of Date's and when someone opens the app on one of said dates I want the confetti to run for 5 seconds. I'm using the realistic confetti.

```
    componentDidMount() {
        const snapshots = [ 
...
]
        if (snapshots.includes(getTimestamp())) {
            this.startAnimation()
            setTimeout(this.pauseAnimation, 2000)
        }

```

My issue is that the animations works, but never stops. I've tried the code above and to set the timeout in pauseAnimation() directly but didn't work. Is there a workaround for this?

Can't use useEffect because it's a class component.

-----

**SOLVED**

Made a countdown timer so that pauseAnimation runs after 5 seconds.

**Comment by ulitcos** [comment]
Hi. It's quite difficult when you don't see all code. However, I think next code can help you:

`setTimeout(() => {this.pauseAnimation()}, 2000)`

or 

`setTimeout(this.pauseAnimation.bind(this), 2000)`
