### ISSUE TITLE
How to draw custom confetti particles using canvas?

### ISSUE THREAD

**Issue by jahirfiquitiva** [ulitcos/react-canvas-confetti#7]
Is there a function that received the canvas or its context as a parameter and allows to draw custom confetti particles?

Similar to https://github.com/alampros/react-confetti#drawshape= ?

If there's no function, could you please allow something like that? (I prefer using this lib)

Thanks in advance.

**Comment by ulitcos** [comment]
Hi there. Unfortunately it can't. I think you should ask that question [here](https://github.com/catdad/canvas-confetti/issues). The thing is react-canvas-confetti is only react component over [canvas-confetti](https://github.com/catdad/canvas-confetti), where happen all magic.

**Comment by jahirfiquitiva** [comment]
Just opened the issue in the other repo. Hopefully they provide a function to achieve this
https://github.com/catdad/canvas-confetti/issues/180
