### ISSUE TITLE
React 18 support

### ISSUE THREAD

**Issue by hichemfantar** [ulitcos/react-canvas-confetti#9]
Does this properly work with React 18?

**Comment by ulitcos** [comment]
Yes, I think everything should work perfectly. I checked the examples on version 18 below by following the links. Did you run into any problems?

https://codesandbox.io/s/fireworks-cl-react-canvas-confetti-forked-tkj37h

https://codesandbox.io/s/school-pride-fn-react-canvas-confetti-forked-v89wrb

**Comment by hichemfantar** [comment]
This warning comes up in the console log.
`Warning: ReactDOM.render is no longer supported in React 18. Use createRoot instead. Until you switch to the new API, your app will behave as if it's running React 17. Learn more: https://reactjs.org/link/switch-to-createroot
`

**Comment by ulitcos** [comment]
This is not a library issue. If you are going to use react 18 you need to use the new [createRoot](https://reactjs.org/docs/react-dom-client.html#createroot) API. Just replace your code


```
const rootElement = document.getElementById("root");
ReactDOM.render(<App />,  rootElement);
```

with that

```
const container = document.getElementById("root");
const root = createRoot(container);
root.render(<App />);
```

**Comment by hichemfantar** [comment]
I thought it was the library using the old api. Thanks!
